"""C++ export parser + state-replay tests."""

from __future__ import annotations

import textwrap
from pathlib import Path

from pix_mcp import cpp_export


SAMPLE_CPP = textwrap.dedent(
    """\
    // Auto-generated by PIX export-to-cpp
    #include "d3d12.h"

    void ReplayFrame(ID3D12GraphicsCommandList* pCommandList)
    {
        // Event 100
        pCommandList->SetGraphicsRootSignature(g_rootSig_default);
        // Event 101
        pCommandList->SetDescriptorHeaps(1, g_heaps);
        // Event 102
        pCommandList->SetPipelineState(g_pso_opaque);
        // Event 103
        pCommandList->SetGraphicsRootDescriptorTable(0, BaseGpuDescriptor + 12);
        // Event 104
        pCommandList->SetGraphicsRootDescriptorTable(1, BaseGpuDescriptor + 40);
        // Event 105
        pCommandList->SetGraphicsRootConstantBufferView(2, 0xDEADBEEFCAFEBABE);
        // Event 106
        pCommandList->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
        // Event 107
        pCommandList->DrawIndexedInstanced(36, 1, 0, 0, 0);

        // ShadowPass starts here
        // Event 200
        pCommandList->SetPipelineState(g_pso_shadow);
        // Event 201
        pCommandList->SetGraphicsRootDescriptorTable(0, BaseGpuDescriptor + 80);
        // Event 202
        pCommandList->DrawIndexedInstanced(12, 1, 0, 0, 0);

        // back to default
        // Event 300
        pCommandList->SetComputeRootSignature(g_rootSig_blur);
        // Event 301
        pCommandList->SetPipelineState(g_pso_blur);
        // Event 302
        pCommandList->SetComputeRootDescriptorTable(0, BaseGpuDescriptor + 160);
        // Event 303
        pCommandList->SetComputeRootUnorderedAccessView(1, 0xCAFEBABE00001234);
        // Event 304
        pCommandList->Dispatch(8, 8, 1);
    }
    """
)


def test_parse_call_count_and_event_ids(tmp_path: Path) -> None:
    src = tmp_path / "frame.cpp"
    src.write_text(SAMPLE_CPP, encoding="utf-8")
    exp = cpp_export.parse_export(tmp_path)
    methods = [e.method for e in exp.events]
    assert methods.count("SetGraphicsRootSignature") == 1
    assert methods.count("SetGraphicsRootDescriptorTable") == 3
    assert methods.count("Dispatch") == 1
    assert 100 in exp.event_ids_seen
    assert 304 in exp.event_ids_seen
    assert len(exp.event_ids_seen) == len({100, 101, 102, 103, 104, 105, 106, 107,
                                           200, 201, 202, 300, 301, 302, 303, 304})


def test_state_at_event_root_param_overwrite(tmp_path: Path) -> None:
    src = tmp_path / "frame.cpp"
    src.write_text(SAMPLE_CPP, encoding="utf-8")
    exp = cpp_export.parse_export(tmp_path)

    # After event 107, graphics root param 0 should reflect the descriptor table
    # set at event 103 (BaseGpuDescriptor + 12), not the shadow one (event 201).
    state = cpp_export.state_at_event(exp, global_id=107, inclusive=True)
    assert state.graphics.pso == "g_pso_opaque"
    assert state.graphics.root_signature == "g_rootSig_default"
    rp0 = state.graphics.root_params.get(0)
    assert rp0 is not None
    assert rp0["kind"] == "descriptor_table"
    assert "BaseGpuDescriptor + 12" in (rp0.get("handle") or rp0.get("raw") or "")

    # After event 202, graphics root param 0 should be the shadow handle and
    # the PSO should have flipped to the shadow PSO.
    state = cpp_export.state_at_event(exp, global_id=202, inclusive=True)
    assert state.graphics.pso == "g_pso_shadow"
    rp0 = state.graphics.root_params.get(0)
    assert "BaseGpuDescriptor + 80" in (rp0["handle"] or rp0["raw"])

    # Graphics root param 2 was set by SetGraphicsRootConstantBufferView at 105.
    assert state.graphics.root_params[2]["kind"] == "cbv"
    assert "0xDEADBEEFCAFEBABE" in state.graphics.root_params[2]["gpu_va"]


def test_compute_pipeline_isolated(tmp_path: Path) -> None:
    src = tmp_path / "frame.cpp"
    src.write_text(SAMPLE_CPP, encoding="utf-8")
    exp = cpp_export.parse_export(tmp_path)

    state = cpp_export.state_at_event(exp, global_id=304, inclusive=True)
    assert state.compute.root_signature == "g_rootSig_blur"
    rp0 = state.compute.root_params.get(0)
    assert rp0 is not None
    assert rp0["kind"] == "descriptor_table"
    rp1 = state.compute.root_params.get(1)
    assert rp1 is not None
    assert rp1["kind"] == "uav"
    assert "0xCAFEBABE00001234" in rp1["gpu_va"]


def test_find_calls_filters(tmp_path: Path) -> None:
    src = tmp_path / "frame.cpp"
    src.write_text(SAMPLE_CPP, encoding="utf-8")
    exp = cpp_export.parse_export(tmp_path)

    draws = cpp_export.find_calls(exp, method_like="Draw")
    assert len(draws) == 2
    assert all("DrawIndexedInstanced" in c.method for c in draws)

    in_shadow = cpp_export.find_calls(exp, between=(200, 299))
    assert {c.global_id for c in in_shadow} == {200, 201, 202}

    by_args = cpp_export.find_calls(exp, args_substring="BaseGpuDescriptor + 80")
    assert len(by_args) == 1
    assert by_args[0].global_id == 201
